imports:
    - { resource: routes_help.yml }

homepage:
    path: /cms/homepage

articles:
    path: /articles

articles_details:
    path: /articles/details/{id}/{title}
    defaults: { id: 0, title: 'default article' }

loanDetails:
    path: /others/loanDetails